server:
  port: 8080
---
spring:
  config:
    activate:
      on-profile: default
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/master/protocol/openid-connect/certs
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: oder
          destination: labshopoauth-keycloak
          contentType: application/json
        event-out:
          destination: labshopoauth-keycloak
          contentType: application/json
logging:
  level:
    org.hibernate.type: info
    org.springframework.cloud: info
    org.springframework.security: debug    


server:
  port: 8081


---
spring:
  config:
    activate:
      on-profile: docker
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://keycloak.keycloak:80/realms/my_realm/protocol/openid-connect/certs
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  cloud:
    stream:
      kafka:
        binder:
          brokers: my-kafka.kafka:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: oder
          destination: labshopoauth-keycloak
          contentType: application/json
        event-out:
          destination: labshopoauth-keycloak
          contentType: application/json
logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug






